#!/usr/bin/env bash
# displays A record information for subdomains of a given domain

check_subdomain() {
    domain="$1"
    sub="$2"
    result=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4, $5}')
    record_type=$(echo "$result" | awk '{print $1}')
    destination=$(echo "$result" | awk '{print $2}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -n "$subdomain" ]; then
    check_subdomain "$domain" "$subdomain"
else
    check_subdomain "$domain" "www"
    check_subdomain "$domain" "lb-01"
    check_subdomain "$domain" "web-01"
    check_subdomain "$domain" "web-02"
fi
